### ISSUE TITLE
Spaces being eaten up when sending a message

### ISSUE THREAD

**Issue by Azenet** [esibun/hitbox-irc-proxy#6]
Hi,

Spaces seems to be eaten up when a message is sent from IRC to Hitbox.
Replacing [this line](https://github.com/esibun/hitbox-irc-proxy/blob/f863ee4/hitbox_irc_server.py#L190) with `t = " ".join(tok[1:])[1:]` seems to work but I'm not sure of the implications of this change.

**Comment by esibun** [comment]
Not sure how this managed to escape testing.  That line looks correct, feel
free to submit a PR.  I'll merge/fix later today.
